### ISSUE TITLE
reference to teamcity found in logs

### ISSUE THREAD

**Issue by MikeWilliams-UK** [Accenture/Ocaramba#405]
We are using Azure Devops pipelines.
Why do the logs show a reference to teamcity

```
2022-09-22 11:40:08.2315|Error|Ocaramba.DriverContext.SaveScreenshot|Test failed: screenshot saved to C:\***\SmokeTests\bin\Release\net6.0\TestOutput\***_2022_09_22_11_40_06_186_browser.png.
 ##teamcity[publishArtifacts 'C:\***\SmokeTests\bin\Release\net6.0\TestOutput\***_2022_09_22_11_40_06_186_browser.png']
```

**Comment by raczeja** [comment]
if you run test in teamcity you can:
![image](https://user-images.githubusercontent.com/12324498/191799519-2a44fc06-46b3-49b3-8de8-427419f311a3.png)
On Azure Devops  that log do nothing, you can ignore it.

**Comment by MikeWilliams-UK** [comment]
My point here is that as we are NOT using team city, there should NOT be any reference to it in the logs emitted by your code.

Please remove the hard coded reference to teamcity in the string and replace with a more generic one.
